package org.vaadin.bread.ui.form.impl.form.factory;

import java.util.List;

import org.vaadin.bread.ui.crud.OperationAction;
import org.vaadin.bread.ui.crud.OperationMode;
import org.vaadin.bread.ui.form.AbstractAutoGeneratedFormFactory;

import com.vaadin.data.HasValue;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Component;
import com.vaadin.ui.GridLayout;
import com.vaadin.ui.Layout;
import com.vaadin.ui.VerticalLayout;

/**
 * @author Alejandro Duarte
 */
public class GridLayoutFormFactory<T, E extends Enum<E>> extends AbstractAutoGeneratedFormFactory<T, E> {

    private int columns;
    private int rows;

    public GridLayoutFormFactory(Class<T> domainType, OperationMode[] operationModes, int columns, int rows) {
        super(domainType, operationModes);
        this.columns = columns;
        this.rows = rows;
    }

    @Override
    public Component buildNewForm(OperationMode operationMode, OperationAction[] operationActions, T domainObject, boolean readOnly) {
        GridLayout gridLayout = new GridLayout(columns, rows);
        gridLayout.setSizeFull();
        gridLayout.setSpacing(true);

        List<HasValue> fields = buildFields(operationMode, domainObject, readOnly);
        fields.stream().forEach(field -> gridLayout.addComponent((Component) field));

        Layout footerLayout = buildFooter(operationMode, operationActions, domainObject);

        VerticalLayout mainLayout = new VerticalLayout(gridLayout, footerLayout);
        mainLayout.setExpandRatio(gridLayout, 1);
        mainLayout.setComponentAlignment(footerLayout, Alignment.BOTTOM_RIGHT);
        mainLayout.setMargin(true);
        mainLayout.setSpacing(true);

        return mainLayout;
    }

}
