package org.vaadin.bread.ui.form.impl.form.factory;

import java.util.List;

import org.vaadin.bread.ui.crud.OperationAction;
import org.vaadin.bread.ui.crud.OperationMode;
import org.vaadin.bread.ui.form.AbstractAutoGeneratedFormFactory;

import com.vaadin.data.HasValue;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Component;
import com.vaadin.ui.FormLayout;
import com.vaadin.ui.Layout;
import com.vaadin.ui.VerticalLayout;

/**
 * @author Alejandro Duarte
 */
public class VerticalFormFactory<T, E extends Enum<E>> extends AbstractAutoGeneratedFormFactory<T, E> {

    public VerticalFormFactory(Class<T> domainType, OperationMode[] operationModes) {
        super(domainType, operationModes);
    }

    @Override
    public Component buildNewForm(OperationMode operationMode, OperationAction[] operationActions, T domainObject, boolean readOnly) {
        FormLayout formLayout = new FormLayout();

        List<HasValue> fields = buildFields(operationMode, domainObject, readOnly);
        fields.stream().forEach(field -> formLayout.addComponent((Component) field));

        Layout footerLayout = buildFooter(operationMode, operationActions, domainObject);

        VerticalLayout mainLayout = new VerticalLayout(formLayout, footerLayout);
        mainLayout.setComponentAlignment(footerLayout, Alignment.BOTTOM_RIGHT);
        mainLayout.setMargin(true);

        return mainLayout;
    }

}
