package org.vaadin.bread.core.ui.form.impl.form.factory;

import java.util.List;

import org.vaadin.bread.core.ui.form.AbstractAutoGeneratedFormFactory;
import org.vaadin.bread.core.ui.form.OperationMode;

import com.vaadin.data.HasValue;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Component;
import com.vaadin.ui.FormLayout;
import com.vaadin.ui.Layout;
import com.vaadin.ui.VerticalLayout;

/**
 * @author Alejandro Duarte
 */
public class FormLayoutFormFactory<T> extends AbstractAutoGeneratedFormFactory<T> {

    public FormLayoutFormFactory(Class<T> domainType, OperationMode[] operationModes) {
        super(domainType, operationModes);
    }

    @Override
    public Component buildNewForm(OperationMode operationMode, T domainObject, boolean readOnly) {
        FormLayout formLayout = new FormLayout();

        List<HasValue> fields = buildFields(operationMode, domainObject, readOnly);
        fields.stream().forEach(field -> formLayout.addComponent((Component) field));

        Layout footerLayout = buildFooter(operationMode, domainObject);

        VerticalLayout mainLayout = new VerticalLayout(formLayout, footerLayout);
        mainLayout.setComponentAlignment(footerLayout, Alignment.BOTTOM_RIGHT);
        mainLayout.setMargin(true);

        return mainLayout;
    }

}
