package org.vaadin.crudui.form.impl.form.factory;

import java.util.List;

import org.vaadin.crudui.crud.Operation;
import org.vaadin.crudui.form.AbstractAutoGeneratedFormFactory;

import com.vaadin.data.HasValue;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Component;
import com.vaadin.ui.FormLayout;
import com.vaadin.ui.Layout;
import com.vaadin.ui.VerticalLayout;

/**
 * @author Alejandro Duarte
 */
public class VerticalFormFactory<T, E extends Enum<E>> extends AbstractAutoGeneratedFormFactory<T, E> {

    public VerticalFormFactory(Class<T> domainType, Operation[] operations) {
        super(domainType, operations);
    }

    @Override
    public Component buildNewForm(Operation operation, T domainObject, boolean readOnly) {
        FormLayout formLayout = new FormLayout();

        List<HasValue> fields = buildFields(operation, domainObject, readOnly);
        fields.stream().forEach(field -> formLayout.addComponent((Component) field));

        Layout footerLayout = buildFooter(operation, domainObject, configurations.get(operation).getOperationListener(operation));

        VerticalLayout mainLayout = new VerticalLayout(formLayout, footerLayout);
        mainLayout.setComponentAlignment(footerLayout, Alignment.BOTTOM_RIGHT);
        mainLayout.setMargin(true);

        return mainLayout;
    }

}
