package org.vaadin.bread.core.ui.bread.impl;

import java.util.List;

import org.vaadin.bread.core.ui.form.AbstractAutoGeneratedFormFactory;
import org.vaadin.bread.core.ui.form.CrudOperation;
import org.vaadin.bread.core.ui.form.FormConfiguration;
import org.vaadin.bread.core.ui.form.OperationMode;
import org.vaadin.bread.core.ui.layout.BreadLayout;
import org.vaadin.bread.core.ui.layout.impl.WindowBasedBreadLayout;

import com.vaadin.data.Binder;
import com.vaadin.data.HasValue;
import com.vaadin.icons.VaadinIcons;
import com.vaadin.ui.AbstractOrderedLayout;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.Grid;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.Notification;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.Window;
import com.vaadin.ui.components.grid.Editor;
import com.vaadin.ui.themes.ValoTheme;

/**
 * @author Alejandro Duarte
 */
public class EditableGridBread<T> extends GridBread<T> {

    protected Editor<T> editor;

    public class GridOnlyCrudFormFactory<T> extends AbstractAutoGeneratedFormFactory<T> {
        public GridOnlyCrudFormFactory(Class<T> domainType) {
            super(domainType, CrudOperation.values());
        }

        @Override
        public AbstractOrderedLayout buildNewForm(OperationMode operationMode, T domainObject, boolean readOnly) {
            throw new UnsupportedOperationException("Building forms is not supported. Grid.Editor is used instead.");
        }

        @Override
        public List<HasValue> buildFields(OperationMode operationMode, T domainObject, boolean readOnly) {
            return super.buildFields(operationMode, domainObject, readOnly);
        }

        @Override
        public FormConfiguration getConfiguration(OperationMode operationMode) {
            return super.getConfiguration(operationMode);
        }

        public Binder<T> getBinder() {
            return binder;
        }
    }

    public EditableGridBread(Class<T> domainType) {
        this(domainType, new WindowBasedBreadLayout());
    }

    public EditableGridBread(Class<T> domainType, BreadLayout crudLayout) {
        super(domainType, crudLayout);
        crudFormFactory = new GridOnlyCrudFormFactory<>(domainType);
        setAddOperationVisible(false);
        setUpdateOperationVisible(false);
    }

    @Override
    public void attach() {
        super.attach();
        configureEditor();
    }

    protected void configureEditor() {
        try {
            getCrudFormFactory().buildFields(CrudOperation.UPDATE, domainType.newInstance(), false);
            editor = gridItemList.getGrid().getEditor();
            editor.setEnabled(true);
            editor.addSaveListener(e -> {
            	T updatedObject = updateOperation.perform(e.getBean());
                try {
                	gridItemList.getDataProvider().refreshItem(updatedObject);
                    gridItemList.asSingleSelect().setValue(updatedObject);
                    Notification.show(savedMessage);
                } catch (Exception ex) {
                    crudFormFactory.showError(CrudOperation.UPDATE, CrudOperation.UPDATE, updatedObject, ex);
                }
            });

            Binder<T> binder = getCrudFormFactory().getBinder();
            editor.setBinder(binder);

            List<String> properties = getCrudFormFactory().getConfiguration(CrudOperation.UPDATE).getPropertiesConfiguration().getVisibleOrderedProperties();

            for (String property : properties) {
                Grid.Column<T, ?> column = gridItemList.getGrid().getColumn(property);
                Binder.Binding<T, ?> binding = binder.getBinding(property).get();
                column.setEditorBinding(binding);
            }
        } catch (InstantiationException e) {
            e.printStackTrace();
        } catch (IllegalAccessException e) {
            e.printStackTrace();
        }
    }

    @Override
    protected void gridSelectionChanged() {
        updateButtons();
    }

    @Override
    protected void addButtonClicked() {
        // TODO: https://github.com/vaadin/framework/pull/10040
    }

    @Override
    protected void updateButtonClicked() {
        // TODO: https://github.com/vaadin/framework/pull/10040
    }

    @Override
    protected void deleteButtonClicked() {
        Button cancel = new Button("Cancel");
        Button delete = new Button("Delete", VaadinIcons.TRASH);
        Label label = new Label("Do you really want to delete the selected item?");

        delete.addStyleName(ValoTheme.BUTTON_DANGER);
        HorizontalLayout buttons = new HorizontalLayout(cancel, delete);

        VerticalLayout layout = new VerticalLayout(label, buttons);
        layout.setComponentAlignment(buttons, Alignment.BOTTOM_RIGHT);

        Window window = new Window("Confirm", layout);
        window.setModal(true);
        getUI().addWindow(window);

        cancel.addClickListener(e -> window.close());

        delete.addClickListener(e -> {
        	T value = gridItemList.asSingleSelect().getValue();
            try {
                deleteOperation.perform(value);
                window.close();
                refreshGrid();
                gridItemList.asSingleSelect().clear();
                Notification.show(deletedMessage);

            } catch (Exception ex) {
                getCrudFormFactory().showError(CrudOperation.DELETE, CrudOperation.DELETE, value, ex);
            }
        });
    }

    @Override
    public GridOnlyCrudFormFactory<T> getCrudFormFactory() {
        return (GridOnlyCrudFormFactory<T>) super.getCrudFormFactory();
    }

}
